### PR TITLE
hotfix/npm-prepare

### PR DESCRIPTION
**Pull request by chazkiker2**
## fix `prepare` script to allow for `npm i`

`npm install git+https://github.com/Light-Labs/ryderserial-proto.git` failed due to unknown `cspell` command. 

This PR fixes build script to allow for successful installation

### CODE REVIEW

**Comment by chazkiker2** [comment]
@MarvinJanssen This is only two commits, and one change — `npm i` failed when I went to work on `ryder-cli-proto` and this PR corrects that build script so people can successfully install.

Sorry for the overlook.

**Comment by chazkiker2** [comment]
(Also, any idea why all my commits are still showing up even though I merged main back in?? Maybe a result of not using squash and rebase...)

**Comment by MarvinJanssen** [comment]
👍

Why are there 40 commits on this PR? Could you fix the branch?

**Comment by chazkiker2** [comment]
lmao yes I was trying to figure that out.

**Comment by chazkiker2** [comment]
fixed PR #7

**Pull request closed without merging**
